version: "3"

services:
  db:
    image: postgres:16.1
    container_name: postgres_pta
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "root"
volumes:
  db-store: